### ISSUE TITLE
VPN server no longer working

### ISSUE THREAD

**Issue by ozskywalker** [ozskywalker/docker-softether#2]
Unable to connect to VPN server.

Also seeing these errors in logs:

```
dmesg: read kernel buffer failed: Operation not permitted
sh: iptables: command not found
sh: iptables: command not found
sh: iptables: command not found
```

**Comment by skydan** [comment]
Weird, 4.25-9656 works fine on my end. Any steps to repro?

**Comment by ozskywalker** [comment]
My test setup was to deploy the container on a local machine, connect via VPN client on iPhone/iPad (my original use case)… of course, could be my end too…
